### ISSUE TITLE
Coming soon to a debugger near you

### ISSUE THREAD

**Issue by KirkMunro** [PSPowerHour/PSPowerHour#100]
```yaml
Title: "Coming soon to a debugger near you"
Name: "Kirk Munro"
Timezone: 'Atlantic Standard Time'
Abstract: |
  Demo of some new functionality that I've been adding to the PowerShell Core debugger.
Twitter: '@poshoholic'
SlackID: '@poshoholic'
Blog: 'https://poshoholic.com'
```
