### ISSUE TITLE
Getting Started: Contributing to PowerShell Core

### ISSUE THREAD

**Issue by vexx32** [PSPowerHour/PSPowerHour#101]
```yaml

Title: "Getting Started with PowerShell Core"
Name: "Joel Sallow"
Timezone: 'Eastern Standard Time'
Abstract: |
  The PowerShell Core repository can be extremely daunting for those of us who live our lives primarily in Powershell itself. However, contributing to PowerShell yourself is one of the most effective ways to get that handy little feature in there that you've always wished was a thing! 
  In this brief look, I will detail how to:
  - Fork the PowerShell/PowerShell repository
  - Set up a local build environment with VS Code
  - Work with git to keep your fork neat, tidy, and easy to work with, and
  - Submit, revise, and work on your pull request in the repository
Twitter: '@vexx32'
SlackID: '@Joel-/u/ta11ow-vexx32'
Blog: 'https://vexx32.github.io'

```
