### ISSUE TITLE
Deep Dive: Working in the Underbelly of the PowerShell Engine

### ISSUE THREAD

**Issue by vexx32** [PSPowerHour/PSPowerHour#102]
```yaml

Title: "Deep Dive: Working in the Underbelly of the PowerShell Engine"
Name: "Joel Sallow"
Timezone: 'Eastern Standard Time'
Abstract: |
  In this Deep Dive, I'll be taking you through the internals of the PowerShell tokenizer, that deepest point where PowerShell's basic building blocks and language tokens are created.
  We'll briefly take a look at how string becomes token, before pulling out the magnifying glass to examine `TryGetNumberValue` and take a look at implementing complex number support in the tokenizer, so that we can use imaginary numbers in our daily administration tasks.
Twitter: '@vexx32'
SlackID: '@Joel-/u/ta11ow-@vexx32'
Blog: 'https://vexx32.github.io/'

```
