### ISSUE TITLE
{WIP} Origami : How does folding work in VScode PS Extension

### ISSUE THREAD

**Issue by glennsarti** [PSPowerHour/PSPowerHour#112]
Work In Progress - Do **not** schedule this in yet

```yaml

Title: Senior Software Engineer
Name: Glenn Sarti
Timezone: W. Australia Standard Time
Abstract: |
  PowerShell Origami : How does code folding work in VScode PS Extension
Twitter: @glennsarti
SlackID: @glennsarti
Blog: https://glennsarti.github.io

I've added the PowerShell Code Folding logic into the VSCode PowerShell Extension.  But how does it do what it does?  This quick talk will go through the concepts of how we take a text file (PS Script) and figure out where we can fold the code.
```
