### ISSUE TITLE
What's New in the World of Toast?

### ISSUE THREAD

**Issue by Windos** [PSPowerHour/PSPowerHour#113]
```yaml
Title: "What's New in the World of Toast?"
Name: "Josh King"
Timezone: 'New Zealand Standard Time'
Abstract: |
  There's a new version of BurntToast on the horizon, with a couple of new features that are worthy of a quick demo. Be one of the first to see the latest cutting edge developments in the world of toast (on Windows)... and maybe a sneak peek of a new community effort to develop a cross-platform notification module.
Twitter: '@WindosNZ'
SlackID: '@windos'
Blog: 'https://king.geek.nz'
```
