### ISSUE TITLE
One approach to testing self-contained scripts with Pester

### ISSUE THREAD

**Issue by nohwnd** [PSPowerHour/PSPowerHour#114]
```yaml
Title: 'One approach to testing self-contained scripts with Pester'
Name: 'Jakub Jareš'
Timezone: 'Europe/Prague'
Abstract: |
  Making a script easy to test and easy to deploy are two conflicting goals. See how to easily import and test your script by using a simple coding convention.
Twitter: '@nohwnd'
SlackID: '@nohwnd'
Blog: 'jakubjares.com'
```
