### ISSUE TITLE
Common mistakes in Pester tests and how to avoid them

### ISSUE THREAD

**Issue by nohwnd** [PSPowerHour/PSPowerHour#115]
```yaml
Title: 'Common mistakes in Pester tests and how to avoid them'
Name: 'Jakub Jareš'
Timezone: 'Europe/Prague'
Abstract: |
  Show few common mistakes in Pester tests and how to avoid them to make your test base better.
Twitter: '@nohwnd'
SlackID: '@nohwnd'
Blog: 'jakubjares.com'
```
