### ISSUE TITLE
Cover your function with Pester unit tests

### ISSUE THREAD

**Issue by nohwnd** [PSPowerHour/PSPowerHour#116]
```yaml
Title: 'Cover your function with Pester unit tests'
Name: 'Jakub Jareš'
Timezone: 'Europe/Prague'
Abstract: |
  Take a simple function and cover it with unit tests using Pester.
Twitter: '@nohwnd'
SlackID: '@nohwnd'
Blog: 'jakubjares.com'
```
