### ISSUE TITLE
Cover your function with Pester integration tests

### ISSUE THREAD

**Issue by nohwnd** [PSPowerHour/PSPowerHour#117]
```yaml
Title: 'Cover your function with Pester integration tests'
Name: 'Jakub Jareš'
Timezone: 'Europe/Prague'
Abstract: |
  Take a simple function and cover it with integration tests using Pester.
Twitter: '@nohwnd'
SlackID: '@nohwnd'
Blog: 'jakubjares.com'
```
