### ISSUE TITLE
Assert: Write less Pester tests to cover more code

### ISSUE THREAD

**Issue by nohwnd** [PSPowerHour/PSPowerHour#118]
```yaml
Title: 'Assert: Write less Pester tests to cover more code'
Name: 'Jakub Jareš'
Timezone: 'Europe/Prague'
Abstract: |
  A quick demo of my Assert module and the benefits it brings to you. I will show how to leverage Assert to compare whole objects, which makes your tests quicker to write and easier to maintain. 
Twitter: '@nohwnd'
SlackID: '@nohwnd'
Blog: 'jakubjares.com'
```
