### ISSUE TITLE
So you want to start a blog, huh?

### ISSUE THREAD

**Issue by steviecoaster** [PSPowerHour/PSPowerHour#119]
```yaml

Title: "So you want to start a blog, huh?"
Name: "Stephen Valdinger"
Timezone: 'Eastern Standard Time'
Abstract: |
  Start a blog with JeykllNow! in 10 minutes or less
Twitter: '@steviecoaster'
SlackID: '@steviecoaster'
Blog: 'steviecoaster.github.io'


```
