### ISSUE TITLE
PowerShell Magic: Argument Transformations

### ISSUE THREAD

**Issue by vexx32** [PSPowerHour/PSPowerHour#120]
```yaml

Title: "PowerShell Magic: Argument Transformations"
Name: "Joel Sallow"
Timezone: 'Eastern Standard Time'
Abstract: |
  Ever had a function that seems to _need_ three or four parameter sets just to handle input appropriately? PowerShell Core, in its quest to cover _literally every base on the planet_ for your convenience, has provided a much more succinct and useful method.
  I'll be covering uses of `System.Management.Automation.ArgumentTransformationAttribute` and how to properly design your own transformation attributes.
Twitter: '@vexx32'
SlackID: 'Joel~@vexx32~/u/ta11ow'
Blog: 'https://vexx32.github.io'
```
