### ISSUE TITLE
Using PowerShell to extend the GUI

### ISSUE THREAD

**Issue by Schlauge** [PSPowerHour/PSPowerHour#121]
```yaml

Title: "Using PowerShell to extend the GUI"
Name: "Phil Bossman"
Timezone: 'Eastern Standard Time'
Abstract: |
  If a vendor gives you a GUI or Tool that doesn't do what you want, you might be stuck!!  But if they offer a PowerShell module or (dare i say it) a PSSnapin, then you might just be in luck.  I'll quickly walk through a challenge I had with a Citrix process, then how I used Powershell to solve it.
This will be mainly about my discovery of the PowerShell Cmdlets offered by the vendor and how I go about making new discoveries in other vendor modules.
Twitter: '@Schlauge'
SlackID: '@Schlauge'

```
