### ISSUE TITLE
Host mkdocs in an Azure Storage Blob

### ISSUE THREAD

**Issue by tomlarse** [PSPowerHour/PSPowerHour#122]
```yaml

Title: "Host mkdocs in an Azure Storage Blob"
Name: "Tom-Inge Larsen"
Timezone: 'W. Europe Standard Time'
Abstract: |
  Writing documentation in Markdown is awesome! So is converting it to html with mkdocs and publishing it using an Azure Storage Blob!
Twitter: '@ti83'
SlackID: '@tom-inge'
Blog: 'https://blog.codesalot.com'

```
