### ISSUE TITLE
Do The -Split!

### ISSUE THREAD

**Issue by IISResetMe** [PSPowerHour/PSPowerHour#127]
```yaml

Title: "Do The -Split!"
Name: "Mathias R. Jessen"
Timezone: 'Central European Standard Time'
Abstract: |
  PowerShell 3.0 brought about two new native regex operators - `-split` and `-replace` - let's take a look at `-split`, what it can do, and how we might apply it in ways you might not have thought about.
Twitter: '@IISResetMe'
Blog: 'https://blog.iisreset.me/'
```
