### ISSUE TITLE
When Runspaces need to have a serious discussion

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PSPowerHour/PSPowerHour#130]
```yaml

Title: "When Runspaces need to have a serious discussion"
Name: "Fred"
Timezone: 'W. Europe Standard Time'
Abstract: |
  Runspaces are an awesome way to speed up execution by parallelizing workloads. Too bad that generally once started, you have no choice but to wait until it is finished in order to gather up the results. This introduction into the PSFramework module's Runspace component shows how to easily start exchanging data between runspaces at runtime, enabling an easy way to coordinate worker threads or coordinating with (or between) longterm background tasks.
Twitter: '@FredWeinmann'
SlackID: 'Fred'
Blog: 'https://allthingspowershell.blogspot.com'
```
