### ISSUE TITLE
PowerShell of things... GUI Edition

### ISSUE THREAD

**Issue by Gaspack** [PSPowerHour/PSPowerHour#134]
```yaml

Title: "PowerShell of things... GUI Edition"
Name: "Gaston Paquette"
Timezone: 'America/Toronto'
Abstract: |
  Building tools for users unfamiliar to PowerShell. But also for PowerShell experts to speed up processes. 

Twitter: '@Gaspaq'
SlackID: 'Optional. Your @name on [powershell.slack.com](bit.ly/psslack)'
Blog: 'Optional. Blog URL'

#####################################################
# IMPORTANT
#   We parse this data as yaml
#   Please use comments (#) for any other information
# IMPORTANT
# # # # # # # # # # # # # # # # # # # # # # # # # # #

# Example proposal
# ################
# Title: "Dealing with Dependencies"
# Name: "Warren Frame'
# Timezone: 'America/New_York'
# Abstract: |
#   Managing dependencies is important.  As you start depending on published modules and libraries, ensuring you're using the expected version of a thing becomes critical!  We'll look at using PSDepend to help
# Twitter: '@pscookiemonster'
# SlackID: '@pscookiemonster'
# Blog: 'https://ramblingcookiemonster.github.io/'

# Notes
#######
# The quotation is intentional
  # It helps with some common quotation that might cause issues (e.g. a ' in the title)
  # Some guidelines [here](https://stackoverflow.com/a/22235064/3067642)
# If you use a newline in your Abstract (do you need to?), indent the next line as well
# Twitter, SlackID, and Blog are optional but help us and viewers find you!
# If you don't specify Twitter or SlackID, be sure to keep track of your GitHub notifications!
# Simple PowerShell function to generate this coming soon
```
