### ISSUE TITLE
Azure Pipelines Speedrun

### ISSUE THREAD

**Issue by Windos** [PSPowerHour/PSPowerHour#135]
```yaml
Title: "Azure Pipelines Speedrun"
Name: "Josh King"
Timezone: 'New Zealand Standard Time'
Abstract: |
  Given an existing PowerShell module, complete with Pester tests, is it possible to wire it into Azure Pipelines and get a successful build (or even release!) in under 10 minutes? Only one way to find out...
Twitter: '@WindosNZ'
SlackID: '@windos'
Blog: 'https://king.geek.nz'
```
