### ISSUE TITLE
Fun with Fonts: Displaying file and folder icons in your terminal

### ISSUE THREAD

**Issue by devblackops** [PSPowerHour/PSPowerHour#138]
```yaml
Title: "Fun with Fonts: Displaying file and folder icons in your terminal"
Name: "Brandon Olin"
Timezone: 'Pacific Standard Time'
Abstract: |
  A look inside my latest PowerShell module Terminal-Icons, 
  which displays custom folder and file icons as well as colors inside your terminal.
Twitter: '@devblackops'
SlackID: '@devblackops'
Blog: 'https://devblackops.io'
```
