### ISSUE TITLE
Managing git and GitHub with the power of PowerShell

### ISSUE THREAD

**Issue by felixfbecker** [PSPowerHour/PSPowerHour#141]
```yaml

Title: "Managing git and GitHub with the power of PowerShell"
Name: "Felix Becker"
Timezone: 'Europe/Berlin'
Abstract: |
  git is a very object-oriented system, but its command line client is
  difficult to use for complex automation.
  GitHub is the most popular git repository host, but can do so much
  more through its powerful API than through its web UI.
  I would like to demo two modules I worked on, PowerGit and PSGitHub,
  that work seamlessly together and make creating advanced automation
  with git and GitHub a breeze.
  I'll show how they make the most out of the PowerShell pipeline,
  output formatting and autocompletion capabilities.
Twitter: '@felixfbecker'

#####################################################
# IMPORTANT
#   We parse this data as yaml
#   Please use comments (#) for any other information
# IMPORTANT
# # # # # # # # # # # # # # # # # # # # # # # # # # #

# Example proposal
# ################
# Title: "Dealing with Dependencies"
# Name: "Warren Frame'
# Timezone: 'America/New_York'
# Abstract: |
#   Managing dependencies is important.  As you start depending on published modules and libraries, ensuring you're using the expected version of a thing becomes critical!  We'll look at using PSDepend to help
# Twitter: '@pscookiemonster'
# SlackID: '@pscookiemonster'
# Blog: 'https://ramblingcookiemonster.github.io/'

# Notes
#######
# The quotation is intentional
  # It helps with some common quotation that might cause issues (e.g. a ' in the title)
  # Some guidelines [here](https://stackoverflow.com/a/22235064/3067642)
# If you use a newline in your Abstract (do you need to?), indent the next line as well
# Twitter, SlackID, and Blog are optional but help us and viewers find you!
# If you don't specify Twitter or SlackID, be sure to keep track of your GitHub notifications!
# Simple PowerShell function to generate this coming soon
```
