### ISSUE TITLE
FSharplets: Cmdlets in F#

### ISSUE THREAD

**Issue by vexx32** [PSPowerHour/PSPowerHour#143]
```yaml

Title: "Writing PowerShell Cmdlets in F#"
Name: "Joel Sallow"
Timezone: 'Eastern Standard Time'
Abstract: |
  PowerShell commands are largely written in PowerShell, or in C#. PowerShell is _fantastic_ for quite a few things, but there are some things that simply work better in compiled languages. C# is highly capable but a very different way of writing things, despite the similar syntax.
  F#'s general style is much more similar in a lot of ways to how PowerShell teaches you to think. It's a functional language built around C# that offers quite a few of its own helper libraries and new types to play with, not to mention its very own brand of language features which help it operate in a way that's vastly more similar to PowerShell itself.
Twitter: '@vexx32'
SlackID: '@Joel'
Blog: 'https://vexx32.github.io'

```
