### ISSUE TITLE
Dispelling Git Rebase Magic

### ISSUE THREAD

**Issue by glennsarti** [PSPowerHour/PSPowerHour#148]
Work In Progress - Do **not** schedule this in yet

```yaml

Title: Senior Software Engineer
Name: Glenn Sarti
Timezone: W. Australia Standard Time
Abstract: |
  Using git rebase can seem magical.  In this quick talk we'll go through how rebasing works 
Twitter: @glennsarti
SlackID: @glennsarti
Blog: https://glennsarti.github.io

Git rebase seems utterly magical when you first see it, but behind the scenes it's using foundational features git.  In this quick talk I'll go through how rebase works and why it's such an absolutely great tool to have in your git belt.
```
