### ISSUE TITLE
ISO 8601: One Date/Time Format to Unite the World

### ISSUE THREAD

**Issue by Windos** [PSPowerHour/PSPowerHour#60]
```yaml
Title: "ISO 8601: One Date/Time Format to Unite the World"
Name: "Josh King"
Timezone: 'New Zealand Standard Time'
Abstract: |
  Working across time zones is hard, it gets even harder when you can't even tell which month someone is referring to. My 9/10/2018 is your 10/9/2018, and am I talking about a date in September or October? Imagine how bad things can get if your module writes dates to disk in an ambiguous format and someone from another country tried to use it... it'll be CHAOS! Luckily this one simple trick will solve all of your time telling needs.
Twitter: '@WindosNZ'
SlackID: '@Windos'
Blog: 'https://king.geek.nz'
```
