### ISSUE TITLE
ProxyCommands

### ISSUE THREAD

**Issue by Jaykul** [PSPowerHour/PSPowerHour#71]
```yaml

Title: "ProxyCommands for fun and function"
Name: "Joel Bennett"
Timezone: 'Eastern Standard Time'
Abstract: |
  I'll demo how you can generate parameter blocks and even full command wrappers using the built-in ProxyCommand generator, and show how to safely modify proxy commands to add parameters and the functionality you need. I'll even highlight a few examples that are out in-the-wild.
Twitter: '@Jaykul'
SlackID: '@Jaykul'
Blog: 'huddledmasses.org'

```
