### ISSUE TITLE
Building Dynamic CloudFormation Templates with VaporShell

### ISSUE THREAD

**Issue by scrthq** [PSPowerHour/PSPowerHour#77]
```yaml
Title: Building Dynamic CloudFormation Templates with VaporShell
Name: Nate Ferrell
Timezone: America/Chicago (CST)
Abstract: |
  Quick demo on the benefits of abstracting CloudFormation 
  template building away from JSON/YAML into PowerShell, how
  to use VaporShell, and some handy tips/tricks.
Twitter: '@scrthq'
SlackID: '@scrthq'
Blog: https://ferrell.io/
```
