### ISSUE TITLE
Quick introduction to Docker Compose for Linux

### ISSUE THREAD

**Issue by ctmcisco** [PSPowerHour/PSPowerHour#78]
```yaml

Title: "Quick introduction to Docker Compose for Linux"
Name: "Francisco Navarro"
Timezone: 'Central Standard Time'
Abstract: |
  Docker Compose is a tool that defines multi-service Docker applications using YAML files. We'll go over how to create the YAML file and deploy a WordPress application using Linux containers. 
Twitter: '@CtmCiscotwt'
SlackID: '@ctmcisco'

```
