### ISSUE TITLE
Using the Automated Lab Framework to deploy a lab on Hyper-V Server 2016

### ISSUE THREAD

**Issue by ctmcisco** [PSPowerHour/PSPowerHour#79]
```yaml

Title: "Using the Automated Lab Framework to deploy a lab on Hyper-V Server 2016"
Name: "Francisco Navarro"
Timezone: 'Central Standard Time'
Abstract: |
  Terraform and Vagrant do not work directly with Hyper-V Server like they do with vSphere or Windows 10 Hyper-V and VirtualBox. I have Hyper-V hosts for my Home Lab. I needed a solution to build labs quickly without spending much time on the mechanism. Enter, Automated Lab. We will go over on how Automated Lab quickly builds and destroys Windows VM labs on Hyper-V Server 2016.
Twitter: '@ctmcisco'
SlackID: '@ctmcisco'

```
