### ISSUE TITLE
Git Rebase: Don't fear the Rebase-r

### ISSUE THREAD

**Issue by ChrisLGardner** [PSPowerHour/PSPowerHour#82]
```yaml

Title: "Git Rebase: Don't fear the Rebase-r"
Name: "Chris Gardner"
Timezone: 'GMT Standard Time'
Abstract: |
  The different options for git rebase, how it works and why to use it. A few demos of them against an example repo too.
Twitter: '@halbaradkenafin'
SlackID: '@halbarad'
Blog: 'https://chrislgardner.github.io'
```
