### ISSUE TITLE
Getting Started with PowerShell Core in AWS Lambda

### ISSUE THREAD

**Issue by scrthq** [PSPowerHour/PSPowerHour#97]
```yaml
Title: Getting Started with PowerShell Core in AWS Lambda
Name: Nate Ferrell
Timezone: America/Chicago (CST)
Abstract: Tips, tricks & gotchas with working PowerShell Core in AWS Lambda
Twitter: '@scrthq'
SlackID: '@scrthq'
Blog: https://ferrell.io/
```
