### ISSUE TITLE
PSFramework - Logging to Graylog

### ISSUE THREAD

**Issue by awickham10** [PSPowerHour/PSPowerHour#99]
```yaml

Title: "Logging to Graylog with PSFramework"
Name: "Andrew Wickham"
Timezone: 'America/New_York'
Abstract: |
  Improve your PowerShell scripts with logging! I'll show you how you can use PSFramework's logging functions to log to a GELF (Graylog) server for enterprise consumption.
Twitter: '@awickham'
SlackID: 
Blog: 'awickham.com'
```
